kind: Pod
apiVersion: v1
metadata:
  name: simple-sample
  labels:
    app: simple-sample
spec:
  containers:
  - name: simple-sample
    image: localhost:5000/simple-sample:local
    imagePullPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: simple-sample
spec:
  selector:
    app: simple-sample
  ports:
  - port: 8080
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: simple-sample-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: simple-sample
          servicePort: 8080
---